---

plugins:
# https://github.com/jest-community/eslint-plugin-jest
  - jest
  - import

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  es2020: true
   jest/globals: true
root: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:import/recommended'
   - 'eslint:recommended'

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
   no-use-before-define: error
    prefer-const: error
    no-multiple-empty-lines: error
    space-in-parens: error
    no-multi-spaces: error
    no-var: error
    semi: error
    indent: [error]
    no-console: off
    linebreak-style: 0
    no-param-reassign: 0
    prefer-destructuring: 0
    no-restricted-syntax: 0
    no-continue: off
    max-len: [error, {comments: 120, code: 120}]
    import/extensions: [error, ignorePackages, {js: always}]
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
